name: network
resolution: workspace
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  presenter:
    path: ../presenter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
