name: app
resolution: workspace
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  network:
    path: ../network
  local_storage:
    path: ../local_storage
  presenter:
    path: ../presenter
  usecase:
    path: ../usecase
  entity:
    path: ../entity
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
