name: presenter
resolution: workspace
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  usecase:
    path: ../usecase
  entity:
    path: ../entity


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
